### ISSUE TITLE
Push not watching changed files from CodeKit

### ISSUE THREAD

**Issue by joshuaiz** [njpanderson/push#12]
- Push version: `0.3.0`
 - VS Code version: `1.22.2`
 - Have you disabled all other extensions and can replicate: Yes

**Steps to replicate:**
1. Edit .scss file
2. File is processed by CodeKit and changes output to .css file
3. Push does not recognize changed .css file

**Any other information?**
I even tried setting my /css directory to be watched by Push and still it cannot track any changes from CodeKit.

The SFTP Sublime plugin uses files since last git commit so that you only need to upload changed files. Something like this could work too but ideally Push should be able to watch for changes outside VS Code a la CodeKit.

Thanks!

**Comment by njpanderson** [comment]
Thanks for the report Joshua - I'll look into it. For now, can you confirm two things:

1) That your .scss file and /css dir are within the project workspace, and 
2) At what level they are sitting respective to the .push.settings.json file? (A quick screenshot or `tree` output of the dir would be useful.

Regarding CVS upload, Push does actually have a similar feature — Just look for "Upload all git working files" or "Add git working files to the queue". (Screenshot below).

<img width="617" alt="screen shot 2018-05-03 at 06 23 23" src="https://user-images.githubusercontent.com/12379690/39560988-97aec5f8-4e9a-11e8-8537-9f2b3890d3df.png">

**Comment by joshuaiz** [comment]
We use our own starter theme for every WordPress project and the tree is shown in the screenshot below. In my case, I am usually working on .scss files which get outputted to the /css directory after processing by CodeKit.

<img width="352" alt="screen shot 2018-05-03 at 12 53 57 am" src="https://user-images.githubusercontent.com/1096738/39561635-81fc68ce-4e6c-11e8-8a2c-c8d047b6e071.png">

I tried with the .push_settings_json in various locations in the theme folder: root level, in /library, etc. I could not get it to add the CodeKit processed .css files to the queue.

But the git thing is super cool...I can just use that in the meantime.

Thanks - this is a great plugin.

**Comment by njpanderson** [comment]
The location of .push.settings.json depends on where you want the local root to be, and will only affect watchers in that there needs to be a settings file at or above the level of the watched file/folder. The setup you've screenshotted above seems to be ok at first glance.

I'm having trouble replicating this issue with either files or folders, so just to make sure we're trying the same things, can you confirm the steps you take to add a watcher to either a directory or file please, and whether or not it then displays in the watcher panel, like so:

<img width="329" alt="screen shot 2018-05-03 at 07 45 45" src="https://user-images.githubusercontent.com/12379690/39562931-ff2dd3b2-4ea5-11e8-96e5-bd8f9715e9b0.png">

Also, the output of Push would be useful: View > Output, then select "Push" from the dropdown:

<img width="191" alt="screen shot 2018-05-03 at 07 46 48" src="https://user-images.githubusercontent.com/12379690/39562952-22be372c-4ea6-11e8-8f69-ecd03d41185c.png">

**Comment by joshuaiz** [comment]
I created a watcher for the library/css directory in the Command Palette and yes it shows up:
<img width="364" alt="screen shot 2018-05-03 at 10 57 09 am" src="https://user-images.githubusercontent.com/1096738/39588244-082a4084-4ec1-11e8-9a79-2e078a2fbfde.png">

Then I made some changes to _base.scss which triggers CodeKit to process and output a new style.css file to library/css. Here is the output (beginning with transferring changes to the functions.php file:
<img width="835" alt="screen shot 2018-05-03 at 11 01 52 am" src="https://user-images.githubusercontent.com/1096738/39588462-6bd08cc4-4ec1-11e8-9a49-7ac1ac10df5d.png">

The style.css file is never added to the upload queue in the panel. And as you can see from the output, /library/css/style.css is not uploaded when I use Control-Command-P.

**Comment by njpanderson** [comment]
Can I ask what triggered the two uploads for style.css and style.css.map in the log? Are you doing that manually?

Just to clarify, in case it's not obvious - the watcher doesn't add anything to the queue, it uploads files immediately when they've changed. I have a feeling this might just be a misunderstanding as to what the watcher does?

**Comment by joshuaiz** [comment]
Ahhhhhh so in that case it *is* working, as long as I enable the watcher on the /css directory. Sorry for the misunderstanding. I guess I would rather it added the watched files to the queue rather than uploading them automatically.

With that, it would be great if Push just tracked changed files more automatically and added them to the upload queue - either via git (as with SFTP in Sublime) or some other means.

Maybe I'm weird but I just like to work and then upload all the changed files when I'm ready with a single key command which was the beauty of SFTP for Sublime. I just use Shift-Command-U-P and it uploads all changed files since the last commit - no other setup, watchers, etc. needed.

**Comment by njpanderson** [comment]
That is definitely something I can consider. Should be an easy enough job to make an option to only add watched files to the queue, as opposed to uploading them immediately. Leave it with me and I'll see what I can do for a future release.

**Comment by joshuaiz** [comment]
Thanks for being so responsive. I tried a bunch of SFTP extensions and yours is already the best by far. Will close this now and keep an eye out.

**Comment by njpanderson** [comment]
@joshuaiz just a note to say that this was quite easy to implement and will be pegged for v0.4. Thanks for the input and feedback!
