### ISSUE TITLE
Command pallet not working

### ISSUE THREAD

**Issue by jimmycook** [njpanderson/push#14]
Push version: 0.4.0
VSCode Version 1.23.0 (1.23.0) 

Upload and watch commands are through an error when used from the command pallet, but they're working on sidebar right click.

The error is 'Running the contributed command:'push.upload' failed.'

I cloned the repo and had a look at the code/did some debugging with breakpoints and as far as I can see it is getting undefined as the parameter to the function that gets registered by the register command function - in the case of push.upload it's the UI.upload function.

**Comment by njpanderson** [comment]
Now fixed in 0.4.1. Do let me know if you have any further issues.
