### ISSUE TITLE
Queue not working anymore

### ISSUE THREAD

**Issue by reverdin** [njpanderson/push#15]
Thank you for reporting an issue! Please make sure you get the following information before submitting:

 - Push version: `0.4.1`
 - VS Code version: `1.23.0`
 - Have you disabled all other extensions and can replicate: Yes

**Steps to replicate:**
When I save a file, it is not queued anymore. Started this morning and was working fine yesterday.
I tried to uninstall and reinstall push plugin.
I tried to recreate a new config file.

But when I save a file, it is note queued.

Checked in extension settings:
 "njpPush.uploadQueue": true 

The download file action is working from the context menu

**Any other information?**
MacOS 10.13.4

**Comment by njpanderson** [comment]
Thanks for reporting, @reverdin - Will have a look tonight and let you know.

**Comment by njpanderson** [comment]
Hey @reverdin - This is fixed in 0.4.2. Thanks again for the report.

**Comment by reverdin** [comment]
Hello @njpanderson. It is working perfectly. Thanks for the quick fix and for your very useful plugin.

**Comment by njpanderson** [comment]
No problem, @reverdin - I'm looking to get a full suite of basic unit testing in place before any more releases now, as reliability is crucial in an extension like this.
