### ISSUE TITLE
Consider removing items from the upload queue if they've been uploaded elsewhere

### ISSUE THREAD

**Issue by neilwhitespace** [njpanderson/push#18]
Thank you for reporting an issue! Please make sure you get the following information before submitting:

 - Push version: `0.4.2`
 - VS Code version: `1.23.0`
 - Have you disabled all other extensions and can replicate: Yes

If a file is in the upload queue and it is uploaded by other means (manual upload, watch) then maybe it should be removed from the upload queue?

**Comment by njpanderson** [comment]
(Done in `18c776c`)
