### ISSUE TITLE
Command: "Create/edit Push configuration" not working with no files open

### ISSUE THREAD

**Issue by reverdin** [njpanderson/push#19]
Thank you for reporting an issue! Please make sure you get the following information before submitting:

 - Push version: `0.4.2`
 - VS Code version: `1.23.1`
 - Have you disabled all other extensions and can replicate: [No]

**Steps to replicate:**
If I go to Command Palette and choose "Push: Create/edit Push configuration" nothing happens. If I do it through the context menu in the file explorer it works as expected.

Not a big issue but was used to do it with the command palette and didn't even remember it was available in the context menu.

**Any other information?**
I think it is not working since VS Code 1.23.1 update

Thanks again for this great plugin

**Comment by njpanderson** [comment]
Should be fixed and pushed to 0.4.3. Thanks for reporting!

**Comment by reverdin** [comment]
Hi thanks for this update but it is not fixing the problem in my case. Still nothing happens from the Command Palette. This is only happening for the "Push: Create/edit Push configuration". All other commands seem to work. But when I use this command nothing happens.
From context menu:
If no file exists it asks for a filename to create
If file exists it opens the file

From Command Palette:
Nothing happens in both cases

Again it is not blocking as there is the context menu and all the other features are working very well.

**Comment by njpanderson** [comment]
Interesting - just so I understand the issue better, does this issue by any chance occur when you don't have any files open in vscode, or does it happen while you're editing a file too?

**Comment by reverdin** [comment]
Hello. Just tested and as soon as I have an opened file in the editor, the Command Palette "Push: Create/edit Push configuration" is working as expected. But with the VS Code Welcome page or no file opened in the editor, nothing happens with the Command Palette.

I think the Command takes the path of the active opened file in the editor and not the path of the folder panel so if not file is opened it doesn't know the path. 

So I thing this is not a bug but a misunderstanding of the plugin from my side. I thought the path was taken from the explorer path.

Thanks again for your help and this plugin.

**Comment by njpanderson** [comment]
That sounds right to me, but the confusion is my fault. Will make it much clearer and/or just make it work without a file open. Leave with me and I'll have resolved in the next minor version. (I don't think this needs to be a patch.)

Thanks again for reporting!

**Comment by njpanderson** [comment]
Apologies - didn't get around to sorting this in 0.4.4. Will peg it for 0.4.5 though.

**Comment by njpanderson** [comment]
Released a fix for this in 0.4.5. Thanks for reporting!
