### ISSUE TITLE
Ignore Glob pattern does not seem to be working

### ISSUE THREAD

**Issue by bugs181** [njpanderson/push#21]
Thank you for reporting an issue! Please make sure you get the following information before submitting:

 - Push version: `0.4.4`
 - VS Code version: `1.24.1`
 - Have you disabled all other extensions and can replicate: [No]

**Steps to replicate:**
I've tried the following without success.

    "SFTP": {
        "ignoreGlobs": ["**/node_modules"]
        "ignoreGlobs": ["**/node_modules/*"]
        "ignoreGlobs": ["**/**/node_modules/*"]
    }

**Any other information?**
In addition to that, deleting files/directories on the remote server that are no longer in the local workspace would be a beneficial feature.

**Comment by njpanderson** [comment]
SFTP — or for that matter, any service settings — don't take an option called ignoreGlobs. That option is defined at the global or workspace level. If you want to set it, use Code > Preferences > Settings (cmd-, on a mac) and add something like the following:

```

    "njpPush.ignoreGlobs": [
        "**/.DS_Store",
        "**/Thumbs.db",
        "**/desktop.ini",
        "**/.git/*",
        "**/.svn/*",
        "**/node_modules/*"
    ]
```

Which will overwrite the default ignoreGlobs setting for Push and add "node_modules" to the list.

If you don't want to do this at the global level, you can do it per workspace, which can be done by selecting "Workspace settings" in the preferences editor.

Hope this helps! Let me know if you're still unsure.
