### ISSUE TITLE
autoUploadQueue doesn't work

### ISSUE THREAD

**Issue by ph55** [njpanderson/push#24]
Thank you for reporting an issue! Please make sure you get the following information before submitting:

 - Push version: `0.4.5`
 - VS Code version: `1.25.1`
- OS: `Windows`

**Steps to replicate:**
![image](https://user-images.githubusercontent.com/1386622/43723058-6e8b11f4-999f-11e8-9213-ace5271afdce.png)

**Comment by njpanderson** [comment]
Hey there @ph55 - From the looks of it you've got the setting within a service settings file, and not the VS Code workspace/global settings. The autoUploadQueue setting is not per-service. See the README in the root of this repo (or the extension's page in vscode) for more information.
