### ISSUE TITLE
File configuration template settings object name

### ISSUE THREAD

**Issue by tbonzai** [njpanderson/push#25]
- Push version: `0.4.5`
 - VS Code version: `1.25.1`
 - Have you disabled all other extensions and can replicate: [Yes|No] Yes

**Steps to replicate:**
1) Use the "Create/Edit Push configuration" option to create a new configuration file.
2) Accept the default file path.
3) Choose "File" as the type
4) Notice that the service gets the name "File", but the service settings object created below it has a service name "SFTP".
5) If after setting the "root" path, you attempt to use this configuration, you will get an error "Cannot read property 'root' of undefined".

**Any other information?**
The resolution is to have the settings object named "File" instead of "SFTP". Ideally the wizard would do this step.

**Comment by njpanderson** [comment]
Thanks for reporting @tbonzai - Will look into it.

**Comment by njpanderson** [comment]
@tbonzai - I've push a fix to `hotfix/file-template-fixes` - Would you care to review, or shall I get this deployed?

**Comment by tbonzai** [comment]
@njpanderson - Thanks for the fast turn around and for the great plugin itself. I don’t have the capability to test it. I’m sure you’ve tested it yourself, so go for the deploy.

**Comment by njpanderson** [comment]
Pushed and deployed, thanks @tbonzai
