### ISSUE TITLE
A transfer service was defined but no configuration could be found within the file at ".push.settings.json"

### ISSUE THREAD

**Issue by ph55** [njpanderson/push#26]
- Push version: `0.4.6`
 - VS Code version: `1.25.1`

Suddenly extension stopped working without changing anything.
I guess it could be update.

Error thrown:
```bash
⚠️ A transfer service was defined but no configuration could be found within the file at ".push.settings.json".
```

Settings file exists and was working.
```json
{
  "service": "SFTP",
  "SFTP": {
    "host": "alex",
    "port": 22,
    "username": "developer",
    "password": "123456",
    "root": "/var/www/project",
    "collisionUploadAction": "overwrite"
  }
}
```

**Comment by njpanderson** [comment]
Getting this too, and it's affecting tests. Thanks for letting me know, and I'll try and get a fix out in the next couple of hours.
