### ISSUE TITLE
Uploading a folder ignores the ignoreGlob setting

### ISSUE THREAD

**Issue by mikeburgh** [njpanderson/push#27]
When watching a folder the ignoreGlob setting is followed, but if I right click and select to upload a folder (eg the root) the glob setting seems to be ignored (all the .git files for example get uploaded).

 - Push version: `0.4.6_rc1`
 - VS Code version: `1.26.0`
 - Have you disabled all other extensions and can replicate: Yes

**Steps to replicate:**
Right click folder and select upload, it will will upload files that are in the ignoreGlob default such as .git if it exists

**Comment by njpanderson** [comment]
Hmm, I'm not seeing this behaviour in the HEAD of `develop`:

```
Running 5 tasks in queue...
ℹ️ SFTP client connected to host <redacted>:22
>> /<redacted>/push-test/standard/ignore-test/.htaccess
>> /<redacted>/push-test/standard/ignore-test/a-good-file.txt
>> /<redacted>/push-test/standard/ignore-test/a-subfolder/another-good-file.txt
>> /<redacted>/push-test/standard/ignore-test/MyThumbs.db
>> /<redacted>/push-test/standard/ignore-test/Thumbs.dbo
```

And an `ls` of that folder produces the following:

```
drwxr-xr-x  12 neilanderson  staff  384 14 Aug 19:54 .
drwxr-xr-x  16 neilanderson  staff  512 17 Aug 06:52 ..
-rw-r--r--   1 neilanderson  staff    0 22 Sep  2017 .DS_Store
drwxr-xr-x   3 neilanderson  staff   96 22 Sep  2017 .git
-rw-r--r--   1 neilanderson  staff   54 28 Oct  2017 .htaccess
drwxr-xr-x   3 neilanderson  staff   96 22 Sep  2017 .svn
-rw-r--r--   1 neilanderson  staff    0 28 Oct  2017 MyThumbs.db
-rw-r--r--   1 neilanderson  staff   25 12 Aug 16:35 Thumbs.db
-rw-r--r--   1 neilanderson  staff    9 12 Aug 16:50 Thumbs.dbo
-rw-r--r--   1 neilanderson  staff   26 15 Aug 22:16 a-good-file.txt
drwxr-xr-x   3 neilanderson  staff   96 22 Sep  2017 a-subfolder
-rw-r--r--   1 neilanderson  staff    0 22 Sep  2017 desktop.ini
```

This is based on the default Push ignoreGlobs settings:

```
"njpPush.ignoreGlobs": [
    "**/.DS_Store",
    "**/Thumbs.db",
    "**/desktop.ini",
    "**/.git/*",
    "**/.svn/*"
  ],
  ```

**Comment by mikeburgh** [comment]
Yes, sorry about wasting your time.. 

I tried again today and cannot get it to do it again.. 

So must have been something messed up on my end. I will keep an eye out if it happens again, and try and dig in more to see what's what.

**Comment by 1600** [comment]
having the same issue here.

**Comment by njpanderson** [comment]
Hey @1600 - thanks for the report - this is a closed issue so if you're having troubles, please start a new issue with version, steps to replicate etc. Thanks!
