### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by frufin** [njpanderson/push#30]
I would like to add a french translation to your project.
If interested, let me know how to help...

**Comment by njpanderson** [comment]
Hi @frufin - That would be fantastic, of course! I am about to release 0.5.0 and with it will come a bunch of new localised strings. I'll stick another note in here when that version is out and we can talk about how you can contribute. For now, I'd review the `src/lang/en_gb.js` file and get a feel for what you'd need to edit.

Generally speaking though, it would consist of you forking the repo, making a new translation file (fr.js) and then submitting a pull request back. 

Thanks again!

**Comment by njpanderson** [comment]
@frufin - If you would like to add translations, please feel free to start within a fork of the repository.

Please have a read up of the "Contributing language files" guide within the [CONTRIBUTING.md](https://github.com/njpanderson/push/blob/develop/.github/CONTRIBUTING.md) file.

If you are having any trouble understanding the context of the english or how the replacement variables (${}, p{} etc) work, just let me know.
