### ISSUE TITLE
Push stops searching for config files at current workspace root

### ISSUE THREAD

**Issue by chrischain** [njpanderson/push#34]
- Push version: 0.5.2
 - VS Code version: 1.27.2
 - Have you disabled all other extensions and can replicate: Yes

**Steps to replicate:**

1. Create a .push.settings.json(c) file at /www/mysite/.
2. Navigate to a subfolder of mysite and open VS Code (i.e. /www/mysite/content/reports/)
3. Attempt to upload a file.  You should receive the error: "A settings file could not be found within your project. Have you created a file matching ".push.settings.json*" yet?"

**Any other information?**
This error occurs because the function findFileInAncestors in paths.js is designed to stop at the root of the current workspace.  Previous versions of Push had a bug that would allow the function to scan in folders above the workspace root, as in the example illustrated above.  This bug is actually a useful feature when you have a site with a lot of content, eliminating the need to have settings files in each of the folders where you might want to focus work efforts without having the entire site loaded as the workspace.

**Comment by njpanderson** [comment]
Thanks @chrischain - if you're able to, can you clone Push down, switch to the `feature/try/unlimited-traversal` branch and give it a bash with the vs code debugger?

If you're unable to do this, I can provide a vsix file of the extension in that state.

**Comment by njpanderson** [comment]
@chrischain - Are you able to test this?

**Comment by njpanderson** [comment]
Ok no problem - just let me know if you manage to!

**Comment by scottyinzeo** [comment]
hey guys : I'm pretty new to this debugging stuff, and didn't completely understand your instructions @njpanderson , but here is what I did to "debug":

1. Cloned the push repo.
2. Opened vscode and added the cloned push folder to the workspace.
3. Press F5 to start debugging.
4. Opened one of my projects that I know has a config file in it's parent's root folder:
```
: /path/to/webdev/
:-----| index.cfm
:-----| .push.settings.jsonc
:-----| /path/to/webdev/projectOne/
```

5. Right-clicked on a file, and selected "Upload File".

Here is what I received in the Debug Console:
```
#NaN 19:34:09.271 [Paths#findFileInAncestors] Looking for settings file in: file:///media/RSPDrives/RSPDrives/Group/Website/2test/sainzeo/intranet/checkReceiptsLog
utils.js:318
#NaN 19:34:09.434 [Push#event] onDidChangeActiveTextEditor
utils.js:318
#NaN 19:34:09.435 [Paths#findFileInAncestors] Looking for settings file in: file:///.
utils.js:318
#NaN 19:34:09.437 [Paths#findFileInAncestors] Looking for settings file in: file:///
utils.js:318
#NaN 19:34:09.439 [Paths#findFileInAncestors] Looking for settings file in: file:///
utils.js:318
#NaN 19:34:09.441 [Push#didChangeActiveTextEditor] Editor switched to extension-output-#2
utils.js:318
#NaN 19:34:09.442 [Push#setContext] hasServiceContext: "false"
utils.js:318
#NaN 19:34:09.942 [Push#setEnvStatus] Setting environment label to false
utils.js:318
#NaN 19:51:21.874 [Paths#findFileInAncestors] Looking for settings file in: file:///media/RSPDrives/RSPDrives/Group/Website/2test/sainzeo/intranet/checkReceiptsLog
```

I apologize in advance if there's an ID10T error...

Scotty

**Comment by njpanderson** [comment]
Ok - I have a feeling you were not in the `unlimited-traversal` branch, @scottyinzeo - I'll be merging it into `develop` tonight which you can feel free to re-test. I've had more testing done myself and am relatively happy with it working so it'll likely end up in a new Sunday/Monday release.

**Comment by njpanderson** [comment]
This is now in v0.6.0 - feel free to create a new issue if you have any problems!
