### ISSUE TITLE
Push cannot find settings file at all after version 0.6.0 update

### ISSUE THREAD

**Issue by chrischain** [njpanderson/push#35]
- Push version: `0.6.0`
 - VS Code version: `1.28.2`
 - Have you disabled all other extensions and can replicate: [No]

I've set "njpPush.limitServiceTraversal": false in my settings.json, but I'm still getting the error "_A settings file could not be found within your project. Have you created a file matching ".push.settings.json*_" yet?" even though the directory directly above the root has a .push.settings.jsonc file.

UPDATE: Actually, Push doesn't work at all now, even with a settings file in the root.  Sorry to be the bearer of bad news... now I'm getting the error message regardless of the limitServiceTraversal setting.

**Any other information?**
Windows 7 Pro SP1

**Comment by njpanderson** [comment]
Just to clarify @chrischain - What is the name of your service file and where is it in relation to a file that you're uploading?

The following template might help produce a tree view:

```
├── dir1
│   ├── .push.settings.jsonc
│   └── a-file.txt
│   └── dir3 <workspace root>
│       ├── another-file.txt
│       └── another-file.jpg
├── dir2
│   ├── .push.settings.jsonc
│   ├── filename2.txt
│   └── another-file.jpg
```

Can you also confirm that the service file is well formed and the name is supported by your glob settings (`settingsFileGlob` / `settingsFilename`).

**Comment by martbean** [comment]
I had the same issue with Push 0.6.0 on Windows 10 but can confirm that v0.6.1 is working correctly. Thanks!

**Comment by chrischain** [comment]
**I can confirm that it is now working as expected for me as well.**  Thanks for the quick fix, Neil!

Just for information, and to answer your questions - here is a tree that represents my setup:

`
/www
├── east
│   ├── .push.settings.jsonc
│   └── lots
│   └── of
│   └── other
│   └── dirs
│   └── app <workspace root>
│       ├── another-file.txt
│       └── another-file.jpg
│   └── anotherdir
│       ├── trunk
│              ├── .push.settings.jsonc
│              └── another-file.jpg
`

As you can see, some of my co-workers decided to embed their SVN trunk/branch/tag directories into their project dirs instead of using the ones above the /www root, so I have separate config files in there for those so that when I push their files they properly map to where they should be.

As for the config files, they are using the default names as above, and I have not made any changes to the glob settings.  They're pretty basic config files:

`
// Push settings file - generated on Fri Aug 10 2018 15:15:14 GMT-0700 (Pacific Daylight Time)
// Note: Comments are supported within Push settings files
{
	"env": "dev",
	"dev": {
		"service": "File",
		"options": {
			"timeZoneOffset": -2,
			"testCollisionTimeDiffs": true,
			"collisionUploadAction": "overwrite",
			"collisionDownloadAction": null,
			"followSymlinks": false,
			"root": "//IISDEV1218/WebDev$/east.dev.thedomain.com/east/app"
		}
	}
}
`

Hope this helps to better understand how your extension is being used... it truly is great, and I appreciate your efforts on it very much!  Now, where can I send you some cash to buy you a pint?  It's the least I can do!  =]

**Comment by njpanderson** [comment]
No problem @chrischain — No worries about the pint, just glad it's all working for you!
