### ISSUE TITLE
macOS: unable to use RSA private key - Unsupported key format

### ISSUE THREAD

**Issue by timothevs** [njpanderson/push#37]
- Push version: `0.6.1`
 - VS Code version: `1.29.0`
 - Have you disabled all other extensions and can replicate: [Yes]

I generated a private/public key pair on my new Mac - 
`ssh-keygen -t rsa`

The private key is present in my home folder on macOS 10.14.1, and I have the correct paths set in the .push.settings.jsonc. Yet whenever I try to save and upload the file in the queue, I get the following error - 

> Error: Cannot parse privateKey: Unsupported key format

The private key is a normal id_rsa file found here - /Volumes/Document/Home/.ssh/id_rsa. I tried both with and without a keyphrase pass.

Any suggestions?

<img width="545" alt="screen shot 2018-11-13 at 4 21 51 pm" src="https://user-images.githubusercontent.com/6641077/48443816-44167800-e760-11e8-97f3-38123fce054d.png">

**Comment by timothevs** [comment]
Yep, no issues at all there - the following command logs me in with/without the keyphrase password (as configured)

ssh timothevs@<ip> -p 8190 (custom port - also defined in the settings of the plugin).

**Comment by njpanderson** [comment]
Can you please:

1) Paste the contents of your `.push.settings.jsonc` (redacting anything sensitive) and any Push related settings within your workspace.
2) Generate a new key pair using the same commands (saving into new files) and send them to me? Feel free use something like paste.ec as they won't get used for anything except my own tests.

Thanks!

**Comment by timothevs** [comment]
Sure! Here's the json file https://pastebin.com/tgR7xDCb, and here's the push related settings in settings.json https://pastebin.com/mcqVubxF

Any secure way of getting the keypair to you? I am a little wary of posting them here.

**Comment by njpanderson** [comment]
If you stick them on paste.ec with a 1 day expiration that should be fine. Assuming you're generating a new keypair that isn't in use anywhere, then there's no security issue.

Just going on what you've sent me so far, it looks like the path you have for your key pair isn't standard (`/Volumes/Document/Home/.ssh/id_rsa`) - Can you try setting this path in the `njpPush. privateSSHKey` workspace setting and see if that works?

**Comment by timothevs** [comment]
Sure, here they are - https://cl.ly/e01d81836fcc Please let me know when you have it, and I will delete the same.

As for the path, that's the first thing I tried. Actually with, or without, it still just looks in /Volumes/Document/Home/.ssh/id_rsa

I tried setting privateSSHKey to the path, and setting the privateSSHKeyPassphrase, to no effect. It seems like Push can find the key just fine.

**Comment by njpanderson** [comment]
Got that now - will have a look and get back to you. Cheers!

**Comment by timothevs** [comment]
Just so you know, the username in the example jsonc has been changed. The name in the id_rsa.pub is the correct one.

**Comment by njpanderson** [comment]
Thanks for the note - I believe the name on the end of the public key is relatively meaningless anyway - it's just used as a memo to sysadmins who need reminded who's key it is.

**Comment by njpanderson** [comment]
Ok this appears to be an issue with newer Mac OS versions creating keys by default in the newer RFC4716 format. This format is as yet unsupported by the version of the underlying SSH library Push uses, so for now, you'll need to generate the key using the older PEM format (which is still being widely used, regardless). You can do this like so:

```
ssh-keygen -t rsa -m PEM
```

This will generate a key that instead of starting with:

```
-----BEGIN OPENSSH PRIVATE KEY-----
...
```

Will start with:

```
-----BEGIN RSA PRIVATE KEY-----
...
```

This older format is well supported and will be supported by Push for the foreseeable future.

In the meantime, I'll look into updating the SSH component, as the newer versions do seem to support the newer format standards.

**Comment by timothevs** [comment]
Brilliant! That fixed it. I had a sneaking feeling it had to do with my version of macOS. Glad that you figured it out. Thank you for the excellent plugin!
