### ISSUE TITLE
Allow files/folders to be watched based on settings in the service file

### ISSUE THREAD

**Issue by njpanderson** [njpanderson/push#39]

**Comment by Zenoo** [comment]
@njpanderson Has this functionality been added yet? The milestone shows 1.6.3 but I can't find any option to achieve it.
Would this allow me to watch the whole project opened on vscode ?

**Comment by njpanderson** [comment]
Hi there @Zenoo - that milestone was out of date. I don't really use it much!

The functionality to watch is already in Push, this issue is specifically to be able to define watchers within a service file.

If you want to watch a whole project, just add a watcher for the root folder (by right clicking in the empty area of the project explorer) and make sure the "Persist Watchers" option is active if you want it to remain active between vscode restarts

**Comment by Zenoo** [comment]
Yes, I was talking about defining them in the config file.

Thanks for the tip on the root folder, didn't know that ! (The Persist Watcher doesn't work though, as mentioned in #48)

**Comment by brunokc** [comment]
I know this is old, but I wanted to add that I just spent an hour looking for that tip on how to add a watcher to the root of the workspace. Did I miss it in the documentation, perhaps? Couldn't figure it out until I saw it written here.
