### ISSUE TITLE
Potential issue with downloading large numbers of files

### ISSUE THREAD

**Issue by neilwhitespace** [njpanderson/push#41]
- Push version: `0.6.1`
 - VS Code version: `~`
 - Have you disabled all other extensions and can replicate: Yes

**Steps to replicate:**
Download a folder containing many files.

**Any other information?**
Push appears to stall.

**Comment by njpanderson** [comment]
Cannot replicate in dev `0.6.2-rc2` - downloaded just under 1400 files with success.

Please re-test in situ using next release.
