### ISSUE TITLE
Push v0.6.2 not working/activating!

### ISSUE THREAD

**Issue by njpanderson** [njpanderson/push#43]
First of all, thank you all for using Push.

I have been informed of an issue with v0.6.2 not correctly instantiating in vscode. This was due to an odd dependency issue which unfortunately was not being caught in testing. I will investigate fully tonight.

Suffice to say a new version has been release (v0.6.22) which has fixed this. Please update your Push extension if you are having issues.

**Comment by GusSalvador** [comment]
Seems to still not be working for me.
I'm on version 0.6.22 and unable to use Push

`command 'push.createServiceConfig' not found`

**Comment by njpanderson** [comment]
Hey @GusSalvador - can you provide some more detail please? I've had a bash at recreating this with the "Create/edit Push service configuration" command but everything seems to be working.

**Comment by GusSalvador** [comment]
Mac OS 10.13.6
Code Version 1.23.1 (1.23.1)
Push v0.6.22

I've tried reinstalling Push but it's as if it's not installed.....I don't see any of the commands or context menus.

Let me know if there's something more specific I can provide or test.

**Comment by njpanderson** [comment]
How strange - this is the same issue but I'd fixed it in 0.6.22 - can you try starting code in `--verbose` mode using the command line, and checking for errors which appear relating to Push?

On a Mac, the command would be `code --verbose`.

**Comment by robertkent87** [comment]
Output I get
`[14881:0205/130206.618678:INFO:CONSOLE(270)] "%c[Extension Host] %cActivating extension 'njp-anderson.push' failed: Unexpected token .... %c(at Object.showMessage (/private/var/folders/yk/0x3c9x513px_cb991y1ky3900000gr/T/AppTranslocation/D2599D18-DDAC-4601-AC97-71CBBEBB5739/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:786:926))", source: file:///private/var/folders/yk/0x3c9x513px_cb991y1ky3900000gr/T/AppTranslocation/D2599D18-DDAC-4601-AC97-71CBBEBB5739/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (270)
[14881:0205/130206.634535:INFO:CONSOLE(3148)] "Activating extension 'njp-anderson.push' failed: Unexpected token ....", source: file:///private/var/folders/yk/0x3c9x513px_cb991y1ky3900000gr/T/AppTranslocation/D2599D18-DDAC-4601-AC97-71CBBEBB5739/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (3148)
[14881:0205/130206.637932:INFO:CONSOLE(270)] "%c[Extension Host] %cActivating extension `njp-anderson.push` failed: ", source: file:///private/var/folders/yk/0x3c9x513px_cb991y1ky3900000gr/T/AppTranslocation/D2599D18-DDAC-4601-AC97-71CBBEBB5739/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (270)`

**Comment by robertkent87** [comment]
Updated Visual Studio Code to 1.30.2 and the issue is resolved

**Comment by GusSalvador** [comment]
Updating to 1.30.2 also resolved my issue.

Oddly VCode was not able to update because I had been running it from my Downloads folder.  Once I moved it to my applications folder it was able to successfully update.

**Comment by njpanderson** [comment]
Thanks for the comments, all - have updated the engine requirements in v0.6.23.
