### ISSUE TITLE
TypeError after VSCode Update to 1.32

### ISSUE THREAD

**Issue by scottyinzeo** [njpanderson/push#44]
- Push version: 0.6.24
 - VS Code version: 1.32.1
 - Have you disabled all other extensions and can replicate: Yes

**Steps to replicate:**
- Modify any file locally and save it.
- Upload the file to your remote server using keyboard shortcut, right-click menu, etc.
- After the file is uploaded, the Console displays with the error message: **TypeError: vscode.window.createStatusBarItem is not a constructor**

**Any other information?**
- The status bar icons for Push no longer display as well
- Files do continue to upload successfully though, but each subsequent upload throws another "TypeError" message

**Comment by njpanderson** [comment]
Thanks for reporting @scottyinzeo - I believe the cause here is an errant `new` keyword in utils.js:80:

```
this._sb = new vscode.window.createStatusBarItem(
	vscode.StatusBarAlignment.left,
	1
);
```

Although I get no errors in any context, and removing the `new` oddly doesn't seem to change the behaviour at all - can you please clarify how you're making an error appear and how it might be affecting the UI?

**Comment by scottyinzeo** [comment]
- Open a new workspace in vscode
- Add folder to workspace or open an existing project (if using project manager) containing the Push settings file (.push.settings.jsonc)
- Open a file, modify and save it
- An icon in the status bar appears from Push stating there is one file ready to upload
- Press CTRL-ALT-U (windows) to upload the file -> file uploads, but Console/Output panel appears stating the error; icon in the status bar continues stating there is one file ready to upload
- If clicking on the Push icon to upload this one file from the status bar, error still occurs, but the Push icon disappears from the status bar
- I've also tried this on a fresh VScode install with just the Push extension installed, and am seeing the same behavior

Other than the error causing the Output panel to constantly appear after uploading a file, it seems like everything else works just fine - it's just annoying 😄

**Comment by njpanderson** [comment]
Should be all sorted now @scottyinzeo - Thanks for the bug report. Let me know if `0.6.25` doesn't fix it!

**Comment by scottyinzeo** [comment]
Looking great!! Thank you thank you thank you!
