### ISSUE TITLE
Auto Push/Pull Config

### ISSUE THREAD

**Issue by RebelCoderRU** [njpanderson/push#45]
Hello.

By reading the dock I tried to configure auto-push (when saved) and auto-pull, when changes on the server are detected. But it does not seem to do that, I have to keep SAVE + PUSH, and PULL manual. Is it possible to fully automate this so it is close to real-time collaboration?

```
My Config:
{
	"env": "default",
	"default": {
		"service": "SFTP",
		"options": {
			// "timeZoneOffset": 0,
			// "testCollisionTimeDiffs": true,
			// "collisionUploadAction": null,
			// "collisionDownloadAction": null,
			// "followSymlinks": false,
			"host": "192.168.1.178",
			// "port": 22,
			"username": "py",
			"password": "pycoder",
			// "privateKey": "",
			// "keyPassphrase": "",
			"root": "py_projects",
			// "keepaliveInterval": 500,
			// "debug": false,
			// "fileMode": "",
			// "sshGateway": null
			"uploadQueue": true,
			"autoUploadQueue": true
		}
	}
}
```

Thanks!

**Comment by njpanderson** [comment]
Hi there @RebelCoderRU - Thanks for submitting the issue!

If I'm understanding this correctly, you're wanting Push to automatically detect file changes on the remote server. That functionality doesn't currently exist in Push and I don't have any plans to add it. To do so would likely require some kind of monitoring agent on the server side which could report file changes. Is there an extension which does this in the marketplace which you know of? Could be an interesting challenge to add this in!

**Comment by demolitions** [comment]
AFAIK no IDE has this specific function, one instance I found something barely similar is an old NetBeans plugin which simply pulls the file when the editor receives focus, and if the file differs (and is not "dirty" in the editor) replaces the local file with the remote.
IIRC the plugin has been discontinued years ago (NetBeans 7 i think) because it was too CPU consuming compared with the benefits.

On a side note, I know there are VSCode extensions that lets the user edit file "directly" on the server, I don't know how they work and how/if they manage this type of collision.

**Comment by alv909** [comment]
I believe @RebelCoderRU made the mistake of putting two issues into one, thereby the main one (IMHO) of simply "configure auto-push (when saved)" got skipped over by accident. This also does not work for me, to auto-upload change-saved files. Push auto-queues but does not auto-upload for me. Here is my push.settings.jsonc... how can I get it to auto-upload?

Second question but very close: watcher does not detect when I merge changes from another branch into my branch, I have to manually pick-out which files changed and manually upload them. How do I get watcher to detect changes through git merges and then, as above, autoupload those changes?

"env": "dev",
	"dev": {
		"service": "SFTP",
		"options": {
			"reminder": true,
			"host": "***",
			"port": 22,
			"username": "***",
			"password": "***",
			"root": "***",
			"autoUploadQueue": true
		}
	}

Thanks!
