### ISSUE TITLE
Line endings not converted between systems

### ISSUE THREAD

**Issue by webtop** [njpanderson/push#46]
- Push version: `0.6.25`
 - VS Code version: `1.33.1`
 - Have you disabled all other extensions and can replicate: No

**Steps to replicate:**
Setup a remote Linux server to deploy to
Run VSC in Windows
Setup a Push config file to push files to the server
Add a Watch on a file (I'm using Python)
Save file with Windows line endings
After push to Linux, check file line endings (they will still be DOS)

**Any other information?**
As long as the user has dos2unix installed on the remote system, that could be ran after a push on each of the pushed files to solve the problem. Ideally though, and option to convert line endings should be added.

Thanks

**Comment by njpanderson** [comment]
Hi @webtop - Thanks for submitting the issue. From what I can tell, you're after a way to convert line endings at the point of uploading, is that correct?

I wonder, if that is the case, whether this is correct to be within the remit of Push, and not vscode itself when managing the files? It feels like I might be opening a lot of problems not only with speed but reliability if Push started manipulating files on upload.

**Comment by webtop** [comment]
I know what you mean. Why can’t vscode detect the OS or even read from configuration, and change the encoding?

The issue became apparent in a Python app I’m writing. Right now every time I save a file and it pushes, if the file has the executable bit set, I have to run dos2unix on the file.

I have a workaround in watching the folder, and running it automatically now, but if rather not have to.

C’est la vie! Not the end of the world.

It ain't easy being green! Please recycle.

**Comment by njpanderson** [comment]
> I know what you mean. Why can’t vscode detect the OS or even read from configuration, and change the encoding?

Hmm, I was under the impression it could! I guess it's not as simple as just doing things automatically though.

> Save file with Windows line endings

With this step, is it essential that you save the file with Windows line endings? Why not save them with unix ones? (I don't know the Windows workflow as well, but whenever I use it at work, we have to ensure our files are saved with unix line endings anyway, even if uploading Windows > Linux) — It's actually caused breakages in the past with PHP.

If there is anything I can do to help in future features, that maybe don't require the editing of files on the fly, do let me know!
