### ISSUE TITLE
persistWatchers not working

### ISSUE THREAD

**Issue by Zenoo** [njpanderson/push#48]
- Push version: `0.7.2`
 - VS Code version: `1.33.1`
 - Have you disabled all other extensions and can replicate: Yes

**Steps to replicate:**
- Watch a file/folder
- Restart VSCode
- The watched files list is now empty

**Any other information?**

Here are the settings I'm using:

```
{
	"env": "dev",
	"dev": {
		"service": "SFTP",
		"options": {
			"host": "xxxxx",
			"port": 66666,
			"username": "xxxx",
			"password": "xxxxx",
			"root": "/xx/xx",
			"persistWatchers": true,
			"reminder": false,
			"ignoreGlobs": [
				"**/.git/*",
				"**/node_modules/*"
			]
		}
	}
}
```

**Comment by njpanderson** [comment]
Hey there, it looks like you’re using the service file to set that option, but it’s a global push option:

https://github.com/njpanderson/push/blob/develop/README.md#extension-settings

You set this in either your global or workspace preferences for vscode.

**Comment by Zenoo** [comment]
Oh yeah I got confused, it works. Thanks !

**Comment by joehanna** [comment]
I know it is late in the game, but for anyone who has struggled to get this to work, here is the VS Code settings.json entry you need:

```
{
  ...,
  "njpPush.persistWatchers": true,
  ...,
}
```
