### ISSUE TITLE
Files are being skipped when selecting any action from the VS Code prompt

### ISSUE THREAD

**Issue by jamesMcMeex** [njpanderson/push#5]
Hey Neil,

I'm seeing an issue when uploading a file or folder that is the same on local as on remote, selecting any action (overwrite, overwrite all etc.) from the dropdown prompt in VS Code results is in the files or folders being skipped and not uploading.

Using ```"collisionUploadAction": "overwrite",```  skips the prompt and the file uploads successfully.

Cheers,
James

**Comment by njpanderson** [comment]
Hey James - This is sorted and will be prepped for release in 1.1.2.
