### ISSUE TITLE
Error: Cannot parse privateKey: Malformed OpenSSH private key. Bad passphrase?

### ISSUE THREAD

**Issue by Jonas1312** [njpanderson/push#50]
- Push version: `0.7.2`
 - VS Code version: `1.36.0`

I have the following error:
```
Running 1 task in queue...
⚠️ Error: Cannot parse privateKey: Malformed OpenSSH private key. Bad passphrase?
```

.push.settings.jsonc:
```
{
	"env": "dev",
	"dev": {
		"service": "SFTP",
		"options": {
			// SFTP Specific options
			"host": "***.fr",
			"username": "*****",
			"password": "*****",
			"root": "/usr/users/****",
			"reminder": false
		}
	}
}
```

When I enter my private ssh key passphrase it works perfectly. However, connecting to this server should not require a ssh key as I'm already providing a username/password.

The ssh key located in c:\users\username\\.ssh should not be read at all if the user provides a username and password in the .push.settings.jsonc file.

Thanks!

**Comment by njpanderson** [comment]
Hi @Jonas1312 can you confirm if this still happens in the latest version? If you're no longer using it fair enough, just drop me a note :)

**Comment by Jonas1312** [comment]
Thanks for your answer @njpanderson. Unfortunately I'm not using this extension anymore and I don't have a remote server to try the latest version, sorry.
