### ISSUE TITLE
Feature : allow to use Pageant (putty SSH agent) on Windows ?

### ISSUE THREAD

**Issue by Indigo744** [njpanderson/push#52]
Hello,

Nice extension.

I have a feature request: on Windows, most of my tools  use Pageant (the putty SSH agent) to get the SSH keys in order to connect to the server.

Would it be possible for Push to support this as well?

Thanks.

**Comment by njpanderson** [comment]
Hey @Indigo744 — If you're still interested, how would you see this working? (I'm not entirely sure what you mean here and I don't have a lot of Windows experience). How is this different from a normal SSH key pair?

**Comment by Pacerino** [comment]
Hey @njpanderson 

I'm not sure if this repository is still active, but I would appreciate it if it is!

Well, I think what @Indigo744 means is that you load the SSH key into Pagent and it is then forwarded when you log in (through sockets etc.). I log in to my server using SSH key. However, this is on my YubiKey so I always have to use the pagent. Unfortunately your extension requires either a password or the direct path to the SSH key.
If you still manage the repo, would it be possible to add this option?

Greetings from Berlin!

**Comment by njpanderson** [comment]
> Unfortunately your extension requires either a password or the direct path to the SSH key.

Hi there @Pacerino — thanks for getting back to me. Unfortunately I'm really not sure what you mean by this. Are you aware that you can provide a path to the SSH key being used within Push at either the general settings, workspace settings, or within each of the server configs?

I'm afraid I don't have much time to work on this anymore, but I am happy to accept PRs if you ever do figure out how to make this more compatible with Pagent or YubiKey—Unfortunately I have absolutely no experience with either systems.
