### ISSUE TITLE
Queue Watcher Persistance Not Working

### ISSUE THREAD

**Issue by jleahy2** [njpanderson/push#53]
- Push version: `0.7.21`
 - VS Code version: `1.38.1`
 - Have you disabled all other extensions and can replicate: Yes

**Steps to replicate:**

- Enable 'Persistent Watchers' in preferences
- Open project, make a change in a watched directory/file
- Save file change
- 'Push' recognizes change, and places file in Queue
- Open another project up
- Return to previous project that had file Queued up in 'Push'
- Queue is empty.

**Any other information?**

**Comment by njpanderson** [comment]
I have not been able to replicate this with multiple tests. Apologies, but if you ever do create a repeatable test, let me know.
