### ISSUE TITLE
Warns of newer file because it is not setting the date in sftp to the original timestamp

### ISSUE THREAD

**Issue by danchaseCTS** [njpanderson/push#54]
- Push version: `0.7.21`
 - VS Code version: `1.40.0`
 - Have you disabled all other extensions and can replicate: [Yes|No] Yes

**Steps to replicate:**
Upload a file that in Windows says any prior date, and it warns that the one it's replacing appears to be newer. When the upload is complete, the timestamp on the file on the server is unchanged.

**Any other information?**
I would have expected it to update the file with the original timestamp, in sFtp this seems to be done with the -p flag I think, but I'm unsure of the implementation.

**Comment by njpanderson** [comment]
The timestamp on the server not changing would be possibly something to do either with the sftp subsystems or the server, neither of which I have any control over.

Can you try another server type (unix) and let me know if it works there? Ideally it should work on all SFTP compatible systems but there will always be edge cases :)

**Comment by danchaseCTS** [comment]
Heya, decided not to be a lazy complainer, and found this issue open on the ssh2 library you're utilizing:

https://github.com/theophilusx/ssh2-sftp-client/issues/15

Seems they can't do it, and are suggesting to use utimes() in order to update the timestamp afterwards. 

So I looked at what sftp put -P does:
put [-P] local-path [remote-path]
Upload local-path and store it on the remote machine. If the remote path name is not specified, it is given the same name it has on the local machine. local-path may contain glob(3) characters and may match multiple files. If it does and remote-path is specified, then remote-path must specify a directory. **If the -P flag is specified, then the file's full permission and access time are copied too.**

So it looks like it modifies the time afterwards, as well.

Messy. I ended up just turning off the warning message and specifying Overwrite instead of Prompt. Looks like they offered to make a sftp.utimes but nobody replied asking them to do so, I searched the source and didn't find it. So it looks like this would be more difficult to fix since you'd have to contribute to that project and get it in via Pull Request, or you could implement your own utimes() at the client level if you wanted (I know you're doing this for the fun of it). If I ever decide to contribute you'll see a PR come through :)

Have a nice day,
Dan Chase

**Comment by njpanderson** [comment]
The odd thing is I've never found an equivalent -p option to be needed within Push. I'd tested all the forms of collision and all of the overwrite options with and without timestamp enforcement, to 100% success.

I wonder if there is something you can maybe manipulate on the server side to avoid the collision dialog popping up without having to pre-request overwrites in the settings (although I suppose most people's use case will be 99% "overwrite" anyway)

And yes, you are correct about my lack of time to spend on this project these days, but if you did do a PR I would happily review :)

Thanks for looking into it further and giving such a comprehensive response!

**Comment by njpanderson** [comment]
Update: I've noticed the SFTP js client has incremented quite a bit since last use, so I'll look into upgrading it when I can.
