### ISSUE TITLE
It would be nice if it would tell you transfer succeeded.

### ISSUE THREAD

**Issue by danchaseCTS** [njpanderson/push#55]
- Push version: `0.7.21`
 - VS Code version: `1.40.0`
 - Have you disabled all other extensions and can replicate: [Yes|No] Yes

**Steps to replicate:**
Upload a file, it just says:
Running 1 task in queue...
ℹ️ SFTP client connected to host ustaclubs.com:22
>> /var/www/html/MobileAppMain.php

But does not tell you if/when it's complete?

**Any other information?**

**Comment by njpanderson** [comment]
This is an option as described in the readme. Push is subtle by default (`queueCompleteMessageType`)

https://github.com/njpanderson/push
