### ISSUE TITLE
Does not work for multiple selected files

### ISSUE THREAD

**Issue by danchaseCTS** [njpanderson/push#56]
- Push version: `0.7.21`
 - VS Code version: `1.40.0`
 - Have you disabled all other extensions and can replicate: [Yes|No] Yes

**Steps to replicate:**
Select two files and click Upload.

Only uploads one of them.

**Any other information?**

**Comment by njpanderson** [comment]
From what I understand, vscode still doesn't send more than the actual file you clicked on in the explorer menu when right clicking on a file. That situation may have changed in recent times. Feel free to let me know by reopening this issue if that is the case.

https://code.visualstudio.com/api/references/contribution-points#contributes.menus

**Comment by danchaseCTS** [comment]
I've created a fix for this, just trying to figure out the pull request for the first time. Coming from my local repository, am I to push straight to develop? My branch is called /feature/MultiFileUpload

**Comment by njpanderson** [comment]
Do a PR into develop and I’ll take a look when I can. Will be interested to see!

**Comment by njpanderson** [comment]
This should now be in v0.7.3. Thanks for flagging!
