### ISSUE TITLE
Inactive notification when pushing files after a short period of inactivity.

### ISSUE THREAD

**Issue by thecesspit** [njpanderson/push#58]
- Push version: `0.7.21`
 - VS Code version: `1.40.2`
 - Have you disabled all other extensions and can replicate: [Yes]

**Steps to replicate:**
-- Probably a configuration setting issue that I can't find the right setting.

Almost every time I push updates to my one environment I get the message"
"The environment "dev" has been inactive for XXXX seconds.  Should Push continue this transfer?"
 It'd be helpful to have this message only for longer inactive periods (600s+ in my case), but I can't work out which config setting deals with this.

**Any other information?**

None.

**Comment by njpanderson** [comment]
Hi there, the readme has information on how to use this. Just look under the [general service settings](https://github.com/njpanderson/push/#general-service-settings) for “reminder” and “reminderTimeout”.

**Comment by thecesspit** [comment]
Thank you, I had indeed failed to find this item.
