### ISSUE TITLE
Installed and now? Where do I go? What could I do to make it work?

### ISSUE THREAD

**Issue by gmsetta** [njpanderson/push#59]
And don't have a clue about version and stuff. All I want to do is to use it. I've downloaded today.

So, it's installed. And now where do I go? How I configure it? Where I find it in VS Code???

 - Push version: `#.#.#`
 - VS Code version: `#.#.#`
 - Have you disabled all other extensions and can replicate: [Yes|No]

**Steps to replicate:**

**Any other information?**

**Comment by njpanderson** [comment]
Hi there, this section if for reporting bugs only. If you’re after user guidance, please check the [readme](https://github.com/njpanderson/push).

**Comment by gmsetta** [comment]
Ok, never mind. Uninstalled anyway. Thks.
