### ISSUE TITLE
Option to remove a file or folder from the upload queue in the explorer window

### ISSUE THREAD

**Issue by jamesMcMeex** [njpanderson/push#6]
Hi Neil,

I've noticed an issue where I can't remove files listed in the upload queue in the explorer.

It would be good to be able to mange the items in this list, if for e.g. you know you don't want to push a certain file that is in the queue by accident.

I came across a scenario today where I changed a file (that was not being watched), then reverted to the original saved version. The file appeared in the upload queue, but I am not able to remove it.

Hope this helps - cheers!

James

**Comment by njpanderson** [comment]
Good catch. Will add it as an enhancement for the next minor.
