### ISSUE TITLE
The file "undefined" could not be found.

### ISSUE THREAD

**Issue by swifft17** [njpanderson/push#68]
- Push version: `0.8.0`
 - VS Code version: `1.41.1`
 - Have you disabled all other extensions and can replicate: No

**Steps to replicate:**
{
  "env": "www.xxxxxxx.com",
  "www.xxxxxxx.com": {
    "service": "SFTP",
    "options": {
      "host": "www.xxxxxxx.com",
      "port": 22,
      "username": "xxx",
      "password": "xxx",
      "root": "/var/www/test",
      "collisionUploadAction": "overwrite"
    }
  }
}

Upload File xxx.php. In Output:
⚠️ The file "undefined" could not be found.

I didn't change any settings. Before last version all worked.

**Any other information?**
Please let me know if you need any other information

**Comment by njpanderson** [comment]
Hi @swifft17 — how are you starting the upload? Which UI are you using and how many files are selected at the time?

**Comment by swifft17** [comment]
I'm using the button, 1 file. And turns out Ctrl+Alt+U is working.

**Comment by njpanderson** [comment]
@swifft17 this is fixed in 0.8.1 — thanks for reporting!
