### ISSUE TITLE
Push to SMB share from Mac

### ISSUE THREAD

**Issue by chrischain** [njpanderson/push#70]
- Push version: `0.8.21`
 - VS Code version: `1.42.1`
 - Have you disabled all other extensions and can replicate: Yes

**Steps to replicate:**
I am attempting to configure Push to send files from my Mac to an SMB share. I've set up the .push.settings.jsonc file as follows:

`
"root": "smb://IISSHARE01658.mycompany.com/WebDev$/easy.dev.mycompany.com/"
`

But when I attempt to push a file, I get the error message:

`Push could not find or access the root path. Please check the ".push.settings.jsonc" settings file.`

**Any other information?**
You'll have to forgive me, this is my first foray into developing on a Mac, so it's probably PEBKAC. This config was originally created on my PC years ago...

**Comment by njpanderson** [comment]
Hi @chrischain - no problem, I can try to make it clearer in the next readme, but Push doesn’t natively support SMB in that sense.

What you do is connect to the SMB server with Finder (CMD-k) and then use a “File” connection in Push with the mounted path as the Push root path. Usually something like `/Volumes/mountpointname`.

So in your case probably something like `/Volumes/IISSHARE01658/WebDev$/easy.dev.mycompany.com `

**Comment by chrischain** [comment]
Ah, that got it of course. Thanks for the info!
