### ISSUE TITLE
Remote execute command after upload

### ISSUE THREAD

**Issue by d1nd141** [njpanderson/push#73]
Hi,

it would be nice to have a feature to execute a remote ssh command after upload.
F.ex. we need to push configuration files to our Splunk deployment server, then execute a command to force distribution (reload).

Thanks

**Comment by njpanderson** [comment]
Hi there @d1nd141 — Thanks for your interest in Push!

While that is an interesting idea, the goal of Push is to keep it simple and predictable. If you're after execution of commands etc on a server, you might want to look into a deployment process more like [Capistrano](https://capistranorb.com) or [Ansible](https://github.com/ansible/ansible), or a Continuous Integration solution such as those which come with GitHub or BitBucket, or products like Travis. All in all, these solutions will give you a much more sustainable deployment process which would likely be beneficial to your projects in the longer term.

Push will remain at its heart an SFTP client, and adding such features would go against my original aim of keep it as basic as possible.
