### ISSUE TITLE
Feature: Local/Remote side-by-side file explorers

### ISSUE THREAD

**Issue by joehanna** [njpanderson/push#78]
- Push version: `0.0.16`
 - VS Code version: `1.47.2`

Push has been the final nail in Coda 2's coffin for me. The queued FTP experience was lacking from VS Code which made it hard for me to switch. Now I can - so thank you!

The other feature I found extremely useful (and I miss from Coda 2) is the side-by-side explorer of local vs remote file systems. I can traverse folders in both windows and I can drag from one to the other. It would be so great to have this built into Push.  The main thing is being able to view the remote file system and open recently edited files to ensure the remote file is present and correct.

I am willing to make a donation towards this feature :)

Thank you!

**Comment by njpanderson** [comment]
Thanks for the request—will consider!
