### ISSUE TITLE
Reduce/Eliminate prompts to confirm transferring queued files

### ISSUE THREAD

**Issue by joehanna** [njpanderson/push#80]
- Push version: `0.8.21`
 - VS Code version: `1.47.2`
 - Have you disabled all other extensions and can replicate: [Yes|No] NO

Step to replicate:
1. Transfer queued files that have changed (I use the Mac keyboard shortcut)
2. Edit some files and save them. Allow 10-15 seconds or so to transpire and then send the queued files.
3. Notice the prompt

![image](https://user-images.githubusercontent.com/1687108/88141085-42d86680-cc36-11ea-8220-35eb53aef673.png)

Is there a way to avoid this? I don't feel it is necessary for my workflow and would like to disable it altogether.

I can't seem to identify a setting for this.

Thanks

**Comment by njpanderson** [comment]
Hi there, this can be controlled by the “reminder” option in the service configs. Thanks!

**Comment by joehanna** [comment]
Thanks for the quick response!
