### ISSUE TITLE
For Watched Folders - always ~ Push: Queue is empty. 

### ISSUE THREAD

**Issue by timothevs** [njpanderson/push#81]
- Push version: `0.8.21`
 - VS Code version: `1.47.2`
 - Have you disabled all other extensions and can replicate: [Yes]

**Steps to replicate:**
Added two folders for minified CSS and JS (using Codekit) to the watched folders. Upon compiling with Codekit, with active changes the  push doesn't fire. 
I save the scss file, Codekit fires, compiles puts it back in the directory called `css`, seems like the Push plugin will do something, but instead I get -> 
`[2020-07-23 13:16:17.726] [renderer3] [error] Queue empty.`
Switched on Debug, nothing - no change is being detected. 
The same works with another plugin just fine SFTP Sync I believe. 

**Any other information?**
I have the SCSS/JS source files in a folder called /source/ which is set to be ignored by Push, so that none of those source files get uploaded. 

Does NOT matter whether I use `ignoreglobs` or not, it will not pick up the changes in the `/css/` folder nor in the `/js/` folder.

Here are my settings
`.push.settings.jsonc`
```jsonc
{
	"env": "prod",
	"prod": {
		"service": "SFTP",
		"options": {
			// "timeZoneOffset": 0,
			// "testCollisionTimeDiffs": true,
			// "collisionUploadAction": null,
			// "collisionDownloadAction": null,
			// "followSymlinks": false,
			"reminder": false,
			// "reminderTimeout": null,
			"host": "<serverIP>",
			// "port": 22,
			"username": "<username>>",
			// "password": "",
			// "privateKey": "",
			// "keyPassphrase": "",
			"root": "/var/www/html/"
			// "keepaliveInterval": 3000,
			// "debug": false,
			// "fileMode": "",
			// "sshGateway": null
		}
	}
}
```

Here's the relevant `settings.json` snippet
```json
    "njpPush.autoUploadQueue": true,
    "njpPush.persistWatchers": true,
    "njpPush.ignoreGlobs": [
        "**/.DS_Store",
        "**/Thumbs.db",
        "**/desktop.ini",
        "**//.git/*",
        "**/.svn/*",
        "**/.vscode/*",
        "**/source/*",
        "**/source/scss/*",
        "**/source/jssrc/*",
        "*.mp4",
        "**/*.avi",
        "**/sftp-config.json",
        "**/*.ttf",
        "**/*.mpg",
        "**/*.wav",
        "**/*.mp3",
        "**/*.ogv",
        "**/*.webm",
        "**/*.pdf",
        "**/*.odf",
        "**/*.sql",
        "**/*.bak",
        "**/*.svg",
        "**/*.jar",
        "**/*.db",
        "**/*.jpg",
        "*.png",
        "**/*.gif",
        "**/*.png",
        "**/*.tif",
        "**/*.ico",
        "**/.gitignore",
        ".gitignore",
        "**/*.ai",
        "**/*.jpeg",
        "**/*.psd",
        "**/**/fonts/*",
        "**/**/temp/*",
        "**/**/_notes/*",
        "**/*.xml",
        "**/*.swf",
        "**/*.csv",
        "**/*.scss",
        "**/*.codekit3",
        "**/*.less",
        "**/videos/*",
        "**/cache/*",
        "**/captcha/*",
        "**/calendar/*",
        "**/feed2js/*",
        "**/uploads/*",
        "**/files/*",
        "**/languages/*",
        "**/pdf/vendor/*",
        "**/config/doctrine/*"
    ],
    "njpPush.disableWatchOnEnvChange": false,

```

**Comment by njpanderson** [comment]
If you're seeing "Queue empty" it means Push is attempting to upload the contents of the Queue, but then not seeing any items.

If this upload isn't something you're triggering, then it's likely the result of the detected file changes in the watched folder. However, the queue being empty isn't helpful at all.

If you're still wondering about this, could you let me know what the queue looks like once this error occurs, and whether or not the behaviour is any different depending on the setting "Auto Upload Queue" turned on/off?
