### ISSUE TITLE
Environment Label not showing reliably

### ISSUE THREAD

**Issue by plueschpruem** [njpanderson/push#83]
- Push version: `0.8.21`
 - VS Code version: `1.47.3` (OSX 10.12.6)
 - Have you disabled all other extensions and can replicate: [No]

**Steps to replicate:**
Make new folder, open with VSC, add push config with 2 environments, wait for selected environment to show up in the toolbar. It doesn't.

Switching it OFF/ON some times globally and for the user _sometimes_ makes the label appear.
But not reliably. I already removed all changed settings to no outcome.
See attached screenshot for one of those moments when it shows up with the option set to false…
![Bildschirmfoto 2020-08-07 um 19 18 30](https://user-images.githubusercontent.com/26715829/89671436-467d1600-d8e3-11ea-9349-7aae309f1ddd.png)

**Comment by njpanderson** [comment]
Due to the way Push works, it’ll only show the environment while a file is open. Is a file open when you try this?

**Comment by plueschpruem** [comment]
aaah! Thanks! Works now.
