### ISSUE TITLE
Is it possible to use environmental variables in the Push configuration?

### ISSUE THREAD

**Issue by plueschpruem** [njpanderson/push#85]
I want to set an environmental variable in `settings.json` and use it to chose my Push environment (and also be used by webpack, etc.).
`${VARNAME}` or `${env:VARNAME}` does not work (just returns the expression as a string), so am I missing anything here, or is it just not possible?

**Comment by njpanderson** [comment]
Hi there, apologies for the late reply, but you are correct in that it is not supported.
