### ISSUE TITLE
Issue with step 2 in quick setup

### ISSUE THREAD

**Issue by karenpayneoregon** [njpanderson/push#86]
First off, thanks for writing this extension.

 - Push version: v0.8.21
 - VS Code version: 1.50.0
 - Have you disabled all other extensions and can replicate: [Yes|No]

**Steps to replicate:**
Under "Quick setup" step 2 when performed results with the following message

a folder for creating a service file could not be found

**Any other information?**
Been using Visual Studio for years, this is my first time in VS Code so not sure if there is something I'm missing.
![11111](https://user-images.githubusercontent.com/17032797/95790611-92a65700-0c94-11eb-828f-f4cf865e30ab.png)

**Comment by njpanderson** [comment]
Hi there - odd! Do you definitely have a folder or project from your file system open?
