### ISSUE TITLE
Empty folders are ignored and not uploaded

### ISSUE THREAD

**Issue by plueschpruem** [njpanderson/push#87]
- Push version: `latest`
 - VS Code version: `latest`
 - Have you disabled all other extensions and can replicate: [Yes]

**Steps to replicate:**
Make an empty folder. Add another empty folder into it.
Upload the outer folder - nothing will transfer.

This is kinda annoying sometimes, for example with a PHP library I use that expects an empty cache folder to exist in a certain place.
Maybe make this an option?

**Comment by njpanderson** [comment]
Hi there @plueschpruem  — thanks for the report.

Push operates on the basis of files, not folders. If a file is in the folder (such as .gitkeep) then it would upload without issue. This would also mean your folder could be stored within the CVS repo without issue as well.

Having a look through the code, I would need to make quite a few changes for this feature, for which I believe the potential for new bugs to creep in would outweigh the benefits.
