### ISSUE TITLE
Permissions for a +x file being reset

### ISSUE THREAD

**Issue by neilwhitespace** [njpanderson/push#9]
Unsure if this is an issue specific to +x or if an assumption to ignore permissions setting unless otherwise requested is needed. Investigate.

**Comment by njpanderson** [comment]
Unable to replicate this. Possibly due to a `fileMode` setting inadvertently migrated from SFTP?

**Comment by neilwhitespace** [comment]
Issue seems to be related to the environment and not Push itself. Cannot replicate this anymore (although the file did lost the +x when I'd logged in, but likely not a Push issue here).
