### ISSUE TITLE
Root set to "/" not working

### ISSUE THREAD

**Issue by swayhead** [njpanderson/push#92]
- Push version: `0.8.21`
 - VS Code version: `1.54.1`

**Steps to replicate:**
Service: SFTP
I set "root" to "/" (which is actually default).
Trying to upload i.e. /htdocs/test.html results in:  Error: sftp.mkdir: Failure /htdocs/test.html/
It's not allowed to leave "root" blank.
Just to check that the transfer works, I set root to "htdocs". The upload succeeds: on the server side it's now /htdocs/htdocs/test.html which is of course not the desirable result.
Any idea how to fix it?
Thanks. Leon

**Comment by njpanderson** [comment]
Have you tried setting the root to `/htdocs`? Sounds like you're chrooted in that SFTP account but `/` might not be the right path to use here.

Please paste your Push config (with any sensitive information redacted), the path location of the settings file within your project and the result of `pwd` over the ssh connection to the server if you are able to.

**Comment by swayhead** [comment]
Setting root to `/htdocs` results in what I mentioned in the first post: a nested folder `/htdocs/htdocs`.

Here goes the config:
```
{
    "env": "LIVE",
    "LIVE": {
      "service": "SFTP",
      "options": {
        "collisionUploadAction": null,
        "host": "...",
        "username": "...",
        "password": "...",
        "root": "/",
         "debug": false,
        "envColours": "#f7ed00"
      }
    }
  }
```
Commenting out the root option does the same.
The settings file is in the project root: `E:\<PROJECT_NAME>\.push.settings.jsonc`
The document root: `E:\<PROJECT_NAME>\htdocs\` 
The SFTP root on the server: `/var/www/<CLIENT_ID>/`
The docroot on the server: `/var/www/<CLIENT_ID>/htdocs/`

Hope it helps. Thanks

**Comment by njpanderson** [comment]
Thanks for the further info! 

Have you tried setting the root to the full path on server? I.e `/var/www/<CLIENT_ID>/htdocs`?

That’s the setting most likely to work. What do you get when it’s set like that?

**Comment by swayhead** [comment]
So, here are some new evidences:
On Mac it works with the same configuration.
On Windows it creates on the server side an empty **directory** (!) `/htdocs/test.html/` when I try to upload a **file** `test.html`. Then it comes with `Error: sftp.mkdir: Failure /htdocs/test.html/`.
Unfortunately, setting the root to the full path does not work. I assume, that´s because the SFTP connection does not recognize any path over its own root.
The error message is `Push could not find or access the root path. Please check the ".push.settings.jsonc" settings file.`
Any thoughts? Thanks!
